kind: pipeline
type: docker
name: default
trigger:
  branch:
    - main
steps:
  - name: validate_spec
    image: alpine:3.17.2
    commands:
      - 'chmod +x ./ci-validate'
      - './ci-validate lephora-server-api.yaml'
